// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.19.1
// source: e_money_service.proto

package e_money_service

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BillerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *BillerRequest) Reset() {
	*x = BillerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e_money_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillerRequest) ProtoMessage() {}

func (x *BillerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_e_money_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillerRequest.ProtoReflect.Descriptor instead.
func (*BillerRequest) Descriptor() ([]byte, []int) {
	return file_e_money_service_proto_rawDescGZIP(), []int{0}
}

func (x *BillerRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type BillerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListBiller []*Biller `protobuf:"bytes,1,rep,name=ListBiller,proto3" json:"ListBiller,omitempty"`
}

func (x *BillerResponse) Reset() {
	*x = BillerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e_money_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillerResponse) ProtoMessage() {}

func (x *BillerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_e_money_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillerResponse.ProtoReflect.Descriptor instead.
func (*BillerResponse) Descriptor() ([]byte, []int) {
	return file_e_money_service_proto_rawDescGZIP(), []int{1}
}

func (x *BillerResponse) GetListBiller() []*Biller {
	if x != nil {
		return x.ListBiller
	}
	return nil
}

type Biller struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Category    string `protobuf:"bytes,2,opt,name=Category,proto3" json:"Category,omitempty"`
	Product     string `protobuf:"bytes,3,opt,name=Product,proto3" json:"Product,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Price       string `protobuf:"bytes,5,opt,name=Price,proto3" json:"Price,omitempty"`
	Fee         string `protobuf:"bytes,6,opt,name=Fee,proto3" json:"Fee,omitempty"`
}

func (x *Biller) Reset() {
	*x = Biller{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e_money_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Biller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Biller) ProtoMessage() {}

func (x *Biller) ProtoReflect() protoreflect.Message {
	mi := &file_e_money_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Biller.ProtoReflect.Descriptor instead.
func (*Biller) Descriptor() ([]byte, []int) {
	return file_e_money_service_proto_rawDescGZIP(), []int{2}
}

func (x *Biller) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Biller) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Biller) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *Biller) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Biller) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Biller) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	NoKartu  string `protobuf:"bytes,3,opt,name=NoKartu,proto3" json:"NoKartu,omitempty"`
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e_money_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_e_money_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_e_money_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBalanceRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GetBalanceRequest) GetNoKartu() string {
	if x != nil {
		return x.NoKartu
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	NoKartu string `protobuf:"bytes,3,opt,name=NoKartu,proto3" json:"NoKartu,omitempty"`
	Balance string `protobuf:"bytes,4,opt,name=Balance,proto3" json:"Balance,omitempty"`
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e_money_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_e_money_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_e_money_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetBalanceResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBalanceResponse) GetNoKartu() string {
	if x != nil {
		return x.NoKartu
	}
	return ""
}

func (x *GetBalanceResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

type CreateEMoneyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Saldo    string `protobuf:"bytes,3,opt,name=Saldo,proto3" json:"Saldo,omitempty"`
}

func (x *CreateEMoneyRequest) Reset() {
	*x = CreateEMoneyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e_money_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEMoneyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEMoneyRequest) ProtoMessage() {}

func (x *CreateEMoneyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_e_money_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEMoneyRequest.ProtoReflect.Descriptor instead.
func (*CreateEMoneyRequest) Descriptor() ([]byte, []int) {
	return file_e_money_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateEMoneyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateEMoneyRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateEMoneyRequest) GetSaldo() string {
	if x != nil {
		return x.Saldo
	}
	return ""
}

type CreateEMoneyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	NoKartu  string `protobuf:"bytes,3,opt,name=NoKartu,proto3" json:"NoKartu,omitempty"`
}

func (x *CreateEMoneyResponse) Reset() {
	*x = CreateEMoneyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e_money_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEMoneyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEMoneyResponse) ProtoMessage() {}

func (x *CreateEMoneyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_e_money_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEMoneyResponse.ProtoReflect.Descriptor instead.
func (*CreateEMoneyResponse) Descriptor() ([]byte, []int) {
	return file_e_money_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateEMoneyResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateEMoneyResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateEMoneyResponse) GetNoKartu() string {
	if x != nil {
		return x.NoKartu
	}
	return ""
}

type GetTrxHistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	NoKartu  string `protobuf:"bytes,3,opt,name=NoKartu,proto3" json:"NoKartu,omitempty"`
}

func (x *GetTrxHistReq) Reset() {
	*x = GetTrxHistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e_money_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrxHistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrxHistReq) ProtoMessage() {}

func (x *GetTrxHistReq) ProtoReflect() protoreflect.Message {
	mi := &file_e_money_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrxHistReq.ProtoReflect.Descriptor instead.
func (*GetTrxHistReq) Descriptor() ([]byte, []int) {
	return file_e_money_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetTrxHistReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTrxHistReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GetTrxHistReq) GetNoKartu() string {
	if x != nil {
		return x.NoKartu
	}
	return ""
}

type GetTrxHistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListTrxHist []*TrxHist `protobuf:"bytes,1,rep,name=ListTrxHist,proto3" json:"ListTrxHist,omitempty"`
}

func (x *GetTrxHistResponse) Reset() {
	*x = GetTrxHistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e_money_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrxHistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrxHistResponse) ProtoMessage() {}

func (x *GetTrxHistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_e_money_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrxHistResponse.ProtoReflect.Descriptor instead.
func (*GetTrxHistResponse) Descriptor() ([]byte, []int) {
	return file_e_money_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetTrxHistResponse) GetListTrxHist() []*TrxHist {
	if x != nil {
		return x.ListTrxHist
	}
	return nil
}

type TrxHist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserId      string `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	NoKartu     string `protobuf:"bytes,3,opt,name=NoKartu,proto3" json:"NoKartu,omitempty"`
	CreatedDate string `protobuf:"bytes,4,opt,name=CreatedDate,proto3" json:"CreatedDate,omitempty"`
	UpdateDate  string `protobuf:"bytes,5,opt,name=UpdateDate,proto3" json:"UpdateDate,omitempty"`
	Setor       string `protobuf:"bytes,6,opt,name=Setor,proto3" json:"Setor,omitempty"`
	Tarik       string `protobuf:"bytes,7,opt,name=Tarik,proto3" json:"Tarik,omitempty"`
	Balance     string `protobuf:"bytes,8,opt,name=Balance,proto3" json:"Balance,omitempty"`
}

func (x *TrxHist) Reset() {
	*x = TrxHist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e_money_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrxHist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrxHist) ProtoMessage() {}

func (x *TrxHist) ProtoReflect() protoreflect.Message {
	mi := &file_e_money_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrxHist.ProtoReflect.Descriptor instead.
func (*TrxHist) Descriptor() ([]byte, []int) {
	return file_e_money_service_proto_rawDescGZIP(), []int{9}
}

func (x *TrxHist) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *TrxHist) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TrxHist) GetNoKartu() string {
	if x != nil {
		return x.NoKartu
	}
	return ""
}

func (x *TrxHist) GetCreatedDate() string {
	if x != nil {
		return x.CreatedDate
	}
	return ""
}

func (x *TrxHist) GetUpdateDate() string {
	if x != nil {
		return x.UpdateDate
	}
	return ""
}

func (x *TrxHist) GetSetor() string {
	if x != nil {
		return x.Setor
	}
	return ""
}

func (x *TrxHist) GetTarik() string {
	if x != nil {
		return x.Tarik
	}
	return ""
}

func (x *TrxHist) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

var File_e_money_service_proto protoreflect.FileDescriptor

var file_e_money_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1f, 0x0a, 0x0d, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x49, 0x0a, 0x0e, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74,
	0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x65,
	0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42,
	0x69, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x65,
	0x72, 0x22, 0x98, 0x01, 0x0a, 0x06, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x46, 0x65,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x46, 0x65, 0x65, 0x22, 0x61, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x6f, 0x4b, 0x61, 0x72, 0x74, 0x75,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4e, 0x6f, 0x4b, 0x61, 0x72, 0x74, 0x75, 0x22,
	0x60, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x4e, 0x6f, 0x4b, 0x61, 0x72, 0x74, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4e, 0x6f, 0x4b, 0x61, 0x72, 0x74, 0x75, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x22, 0x5f, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x4d, 0x6f, 0x6e, 0x65,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x53, 0x61, 0x6c, 0x64, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x61, 0x6c,
	0x64, 0x6f, 0x22, 0x64, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x4d, 0x6f, 0x6e,
	0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x4e, 0x6f, 0x4b, 0x61, 0x72, 0x74, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4e, 0x6f, 0x4b, 0x61, 0x72, 0x74, 0x75, 0x22, 0x5d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54,
	0x72, 0x78, 0x48, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x4e, 0x6f, 0x4b, 0x61, 0x72, 0x74, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4e, 0x6f, 0x4b, 0x61, 0x72, 0x74, 0x75, 0x22, 0x50, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x72,
	0x78, 0x48, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a,
	0x0b, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x78, 0x48, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x72, 0x78, 0x48, 0x69, 0x73, 0x74, 0x52, 0x0b, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x72, 0x78, 0x48, 0x69, 0x73, 0x74, 0x22, 0xd3, 0x01, 0x0a, 0x07, 0x54, 0x72,
	0x78, 0x48, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x4e, 0x6f, 0x4b, 0x61, 0x72, 0x74, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4e, 0x6f, 0x4b, 0x61, 0x72, 0x74, 0x75, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x65, 0x74,
	0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x65, 0x74, 0x6f, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x61, 0x72, 0x69, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x54, 0x61, 0x72, 0x69, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x32,
	0xa6, 0x03, 0x0a, 0x0d, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x45, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x12,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1f, 0x2e, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x65,
	0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0c, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x65, 0x5f, 0x6d, 0x6f, 0x6e,
	0x65, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x65, 0x5f, 0x6d, 0x6f, 0x6e,
	0x65, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x65,
	0x72, 0x12, 0x55, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x22, 0x2e, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x45, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x24, 0x2e, 0x65, 0x5f, 0x6d, 0x6f, 0x6e,
	0x65, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x45, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x54, 0x72, 0x78, 0x48,
	0x69, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x78, 0x48, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x78, 0x48, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x3b, 0x65,
	0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_e_money_service_proto_rawDescOnce sync.Once
	file_e_money_service_proto_rawDescData = file_e_money_service_proto_rawDesc
)

func file_e_money_service_proto_rawDescGZIP() []byte {
	file_e_money_service_proto_rawDescOnce.Do(func() {
		file_e_money_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_e_money_service_proto_rawDescData)
	})
	return file_e_money_service_proto_rawDescData
}

var file_e_money_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_e_money_service_proto_goTypes = []interface{}{
	(*BillerRequest)(nil),        // 0: e_money_service.BillerRequest
	(*BillerResponse)(nil),       // 1: e_money_service.BillerResponse
	(*Biller)(nil),               // 2: e_money_service.Biller
	(*GetBalanceRequest)(nil),    // 3: e_money_service.GetBalanceRequest
	(*GetBalanceResponse)(nil),   // 4: e_money_service.GetBalanceResponse
	(*CreateEMoneyRequest)(nil),  // 5: e_money_service.CreateEMoneyRequest
	(*CreateEMoneyResponse)(nil), // 6: e_money_service.CreateEMoneyResponse
	(*GetTrxHistReq)(nil),        // 7: e_money_service.GetTrxHistReq
	(*GetTrxHistResponse)(nil),   // 8: e_money_service.GetTrxHistResponse
	(*TrxHist)(nil),              // 9: e_money_service.TrxHist
	(*emptypb.Empty)(nil),        // 10: google.protobuf.Empty
}
var file_e_money_service_proto_depIdxs = []int32{
	2,  // 0: e_money_service.BillerResponse.ListBiller:type_name -> e_money_service.Biller
	9,  // 1: e_money_service.GetTrxHistResponse.ListTrxHist:type_name -> e_money_service.TrxHist
	10, // 2: e_money_service.BillerService.ListBiller:input_type -> google.protobuf.Empty
	0,  // 3: e_money_service.BillerService.DetailBiller:input_type -> e_money_service.BillerRequest
	3,  // 4: e_money_service.BillerService.GetBalance:input_type -> e_money_service.GetBalanceRequest
	5,  // 5: e_money_service.BillerService.CreateEMoney:input_type -> e_money_service.CreateEMoneyRequest
	7,  // 6: e_money_service.BillerService.GetTrxHist:input_type -> e_money_service.GetTrxHistReq
	1,  // 7: e_money_service.BillerService.ListBiller:output_type -> e_money_service.BillerResponse
	2,  // 8: e_money_service.BillerService.DetailBiller:output_type -> e_money_service.Biller
	4,  // 9: e_money_service.BillerService.GetBalance:output_type -> e_money_service.GetBalanceResponse
	6,  // 10: e_money_service.BillerService.CreateEMoney:output_type -> e_money_service.CreateEMoneyResponse
	8,  // 11: e_money_service.BillerService.GetTrxHist:output_type -> e_money_service.GetTrxHistResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_e_money_service_proto_init() }
func file_e_money_service_proto_init() {
	if File_e_money_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_e_money_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e_money_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e_money_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Biller); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e_money_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e_money_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBalanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e_money_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEMoneyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e_money_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEMoneyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e_money_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrxHistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e_money_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrxHistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e_money_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrxHist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_e_money_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_e_money_service_proto_goTypes,
		DependencyIndexes: file_e_money_service_proto_depIdxs,
		MessageInfos:      file_e_money_service_proto_msgTypes,
	}.Build()
	File_e_money_service_proto = out.File
	file_e_money_service_proto_rawDesc = nil
	file_e_money_service_proto_goTypes = nil
	file_e_money_service_proto_depIdxs = nil
}
