// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package user_management

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// TransactionNotpoolServiceClient is the client API for TransactionNotpoolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionNotpoolServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type transactionNotpoolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionNotpoolServiceClient(cc grpc.ClientConnInterface) TransactionNotpoolServiceClient {
	return &transactionNotpoolServiceClient{cc}
}

func (c *transactionNotpoolServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/user_management.TransactionNotpoolService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionNotpoolServiceServer is the server API for TransactionNotpoolService service.
// All implementations should embed UnimplementedTransactionNotpoolServiceServer
// for forward compatibility
type TransactionNotpoolServiceServer interface {
	Login(context.Context, *LoginRequest) (*emptypb.Empty, error)
}

// UnimplementedTransactionNotpoolServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTransactionNotpoolServiceServer struct {
}

func (UnimplementedTransactionNotpoolServiceServer) Login(context.Context, *LoginRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

// UnsafeTransactionNotpoolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionNotpoolServiceServer will
// result in compilation errors.
type UnsafeTransactionNotpoolServiceServer interface {
	mustEmbedUnimplementedTransactionNotpoolServiceServer()
}

func RegisterTransactionNotpoolServiceServer(s grpc.ServiceRegistrar, srv TransactionNotpoolServiceServer) {
	s.RegisterService(&_TransactionNotpoolService_serviceDesc, srv)
}

func _TransactionNotpoolService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionNotpoolServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_management.TransactionNotpoolService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionNotpoolServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransactionNotpoolService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user_management.TransactionNotpoolService",
	HandlerType: (*TransactionNotpoolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _TransactionNotpoolService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_mangement.proto",
}
